print('Hello world!\nHello Python!\nHello Guido!')
print()
print('Hello world!\rHello Python! Hello Guido!')
print()
print('Hello world!\b Hello Python!\b\b\b Hello Guido!')
print()
print('Hello world!\tHello Python!\tHello Guido!')
print('Hello world!    Hello Python!    Hello Guido!')
print()
print('Hello world!\n\tHello Python!\n\t\tHello Guido!')

